gos_web_socket:
  server:

    # The host IP address on the server which connections for the websocket server are accepted.
    host: 127.0.0.1

    # The port on the server which connections for the websocket server are accepted.
    port: ~ # Required

    tls:

      # Enables the native tls support that can be configured with the options below.
      enabled: false

      # The options to set up the tls configuration. See the example below or see https://www.php.net/manual/en/context.ssl.php for all available options.
      options:
        local_cert: '/path/to/cert/cert.crt'
        local_pk: '/path/to/key/mykey.key'
        verify_peer: false

    # Enables checking the Origin header of websocket connections for allowed values.
    origin_check: false

    # Enables checking the originating IP address of websocket connections for blocked addresses.
    ip_address_check: false

    # Flag indicating a keepalive ping should be enabled on the server.
    keepalive_ping: false

    # The time in seconds between each keepalive ping.
    keepalive_interval: 30
