knp_paginator:
  page_range: 6
  page_limit: 5000
  convert_exception: false
  remove_first_page_param: false
  default_options:
    page_out_of_range: 1
    page_name: offset                 # page query parameter name
    sort_field_name: sort           # sort field query parameter name
    sort_direction_name: direction  # sort direction query parameter name
    distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
    filter_field_name: filterField  # filter field query parameter name
    filter_value_name: filterValue  # filter value query paameter name
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
    sortable: '@KnpPaginator/Pagination/twitter_bootstrap_v4_font_awesome_sortable_link.html.twig' # sort link template
    filtration: '@KnpPaginator/Pagination/twitter_bootstrap_v4_filtration.html.twig'  # filters template
