<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250205140652 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blog_meta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(1000) DEFAULT NULL, keywords VARCHAR(100) NOT NULL, author VARCHAR(255) NOT NULL, blog_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_372298A5AA5FB55E ON blog_meta (keywords)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_372298A5DAE07E97 ON blog_meta (blog_id)');
        $this->addSql('ALTER TABLE blog_meta ADD CONSTRAINT FK_372298A5DAE07E97 FOREIGN KEY (blog_id) REFERENCES blogs (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comments ALTER parent_id SET DEFAULT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A727ACA70 FOREIGN KEY (parent_id) REFERENCES comments (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5F9E962A727ACA70 ON comments (parent_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blog_meta DROP CONSTRAINT FK_372298A5DAE07E97');
        $this->addSql('DROP TABLE blog_meta');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT FK_5F9E962A727ACA70');
        $this->addSql('DROP INDEX IDX_5F9E962A727ACA70');
        $this->addSql('ALTER TABLE comments ALTER parent_id DROP NOT NULL');
    }
}
